version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: contract_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: contract_intelligence
    volumes:
      - mongodb_data:/data/db
    networks:
      - contract_network

  redis:
    image: redis:7.2-alpine
    container_name: contract_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - contract_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contract_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/contract_intelligence?authSource=admin
      - REDIS_URL=redis://redis:6379
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - contract_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contract_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - contract_network

volumes:
  mongodb_data:
  redis_data:

networks:
  contract_network:
    driver: bridge
